repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 24.2.0 # Updated rev for black hook
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: v5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.3
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
        additional_dependencies:
        - pydantic>=2.0.0
        - sqlalchemy>=2.0.0
        - types-requests
        - types-tabulate
# -   repo: local  # Commenting out pytest hook
#     hooks:
#     -   id: pytest
#         name: pytest
#         entry: python -m pytest -xvs
#         language: system
#         pass_filenames: false
#         always_run: true
exclude: '^pytest_env/bin/'
